import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Heart, ShoppingCart, ArrowLeft, LogIn } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
export default function BookDetailHeader({ book, isFavourite, onToggleFavourite, onAddToCart, isAuthenticated }) {
    const navigate = useNavigate();
    return (_jsxs(_Fragment, { children: [_jsxs("button", { onClick: () => navigate(-1), className: "flex items-center gap-2 text-stone-500 hover:text-stone-900 mb-6 transition-colors", children: [_jsx(ArrowLeft, { className: "h-4 w-4" }), _jsx("span", { children: "Zp\u011Bt na knihy" })] }), _jsx("div", { className: "bg-white rounded-3xl shadow-sm border border-stone-100 overflow-hidden", children: _jsxs("div", { className: "flex flex-col md:flex-row", children: [_jsx("div", { className: "md:w-1/3 bg-stone-100 p-8 flex items-center justify-center", children: book.coverImageUrl ? (_jsx("img", { src: book.coverImageUrl, alt: book.title, className: "w-full max-w-xs rounded-lg shadow-lg" })) : (_jsx("div", { className: "w-full max-w-xs aspect-[3/4] bg-stone-200 rounded-lg flex items-center justify-center", children: _jsxs("div", { className: "text-center text-stone-400", children: [_jsx("div", { className: "text-4xl mb-2", children: "\uD83D\uDCDA" }), _jsx("div", { children: "Bez ob\u00E1lky" })] }) })) }), _jsxs("div", { className: "md:w-2/3 p-8 md:p-12 flex flex-col", children: [_jsxs("div", { className: "flex items-center gap-2 mb-3", children: [book.genre && (_jsx("span", { className: "px-3 py-1 bg-blue-50 text-blue-700 text-xs font-bold uppercase tracking-wider rounded-full", children: book.genre })), book.rating && (_jsxs("div", { className: "flex items-center text-amber-500 text-sm font-medium", children: [_jsx("span", { className: "text-lg", children: "\u2B50" }), _jsx("span", { className: "ml-1", children: book.rating.toFixed(1) }), book.totalRatings && (_jsxs("span", { className: "text-stone-500 ml-1", children: ["(", book.totalRatings, ")"] }))] }))] }), _jsx("h1", { className: "text-3xl md:text-4xl font-bold text-stone-900 mb-2", children: book.title }), _jsxs("p", { className: "text-xl text-stone-500 mb-6", children: ["od ", book.author] }), book.description && (_jsx("p", { className: "text-stone-600 mb-8 leading-relaxed", children: book.description })), _jsxs("div", { className: "grid grid-cols-2 gap-4 mb-8 text-sm text-stone-600 bg-stone-50 p-4 rounded-2xl", children: [book.publicationYear && (_jsxs("div", { children: [_jsx("span", { className: "font-medium text-stone-900", children: "Rok vyd\u00E1n\u00ED:" }), " ", book.publicationYear] })), book.pageCount && (_jsxs("div", { children: [_jsx("span", { className: "font-medium text-stone-900", children: "Po\u010Det stran:" }), " ", book.pageCount] }))] }), _jsxs("div", { className: "flex items-center justify-between pt-6 border-t border-stone-100 mt-auto gap-4", children: [book.price && (_jsxs("div", { className: "text-3xl font-bold text-stone-900", children: [book.price, " K\u010D"] })), _jsxs("div", { className: "flex gap-3", children: [_jsx("button", { onClick: onToggleFavourite, className: `flex items-center gap-2 px-6 py-3 rounded-xl font-medium transition-all ${isFavourite
                                                        ? 'bg-red-50 text-red-600 hover:bg-red-100'
                                                        : 'bg-stone-100 text-stone-600 hover:bg-stone-200'}`, children: _jsx(Heart, { className: `h-5 w-5 ${isFavourite ? 'fill-current' : ''}` }) }), isAuthenticated ? (_jsxs("button", { onClick: onAddToCart, className: "flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-xl font-medium transition-all hover:shadow-lg", children: [_jsx(ShoppingCart, { className: "h-5 w-5" }), "Do ko\u0161\u00EDku"] })) : (_jsxs("button", { onClick: () => navigate('/login'), className: "flex items-center gap-2 bg-stone-600 hover:bg-stone-700 text-white px-6 py-3 rounded-xl font-medium transition-all hover:shadow-lg", children: [_jsx(LogIn, { className: "h-5 w-5" }), "Pro n\u00E1kup se p\u0159ihla\u0161te"] }))] })] })] })] }) })] }));
}
