import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
export default function BooksGrid({ booksResponse, loading, error, onRetry, hasActiveFilters, onClearFilters }) {
    if (loading) {
        return (_jsx("div", { className: "text-center py-12", children: _jsx("div", { className: "text-stone-600", children: "Na\u010D\u00EDt\u00E1n\u00ED knih..." }) }));
    }
    if (error) {
        return (_jsxs("div", { className: "text-center py-12", children: [_jsx("div", { className: "text-red-600 mb-4", children: error }), _jsx("button", { onClick: onRetry, className: "bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-xl transition-colors", children: "Zkusit znovu" })] }));
    }
    return (_jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "text-center space-y-4 mb-8", children: [_jsx("h1", { className: "text-3xl font-bold text-stone-900", children: "Knihy" }), _jsx("p", { className: "text-stone-600 max-w-2xl mx-auto", children: "Prohl\u00E9dn\u011Bte si na\u0161i sb\u00EDrku knih a najd\u011Bte si tu pravou pro v\u00E1s." })] }), booksResponse && booksResponse.books.length > 0 ? (_jsxs(_Fragment, { children: [_jsxs("div", { className: "text-stone-600 text-center mb-6", children: ["Zobrazeno ", booksResponse.books.length, " z ", booksResponse.totalRecords, " knih"] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6", children: booksResponse.books.map((book) => (_jsxs(Link, { to: `/books/${book.id}`, className: "bg-white rounded-2xl shadow-sm border border-stone-200 overflow-hidden hover:shadow-md transition-shadow group", children: [_jsx("div", { className: "aspect-[3/4] bg-stone-100 flex items-center justify-center", children: book.coverImageUrl ? (_jsx("img", { src: book.coverImageUrl, alt: book.title, className: "w-full h-full object-cover" })) : (_jsxs("div", { className: "text-stone-400 text-center p-4", children: [_jsx("div", { className: "text-4xl mb-2", children: "\uD83D\uDCDA" }), _jsx("div", { className: "text-sm", children: "Bez ob\u00E1lky" })] })) }), _jsxs("div", { className: "p-4", children: [_jsx("h3", { className: "font-semibold text-stone-900 mb-1 line-clamp-2 group-hover:text-blue-600 transition-colors", children: book.title }), _jsx("p", { className: "text-stone-600 text-sm mb-2", children: book.author }), book.genre && (_jsx("span", { className: "inline-block bg-stone-100 text-stone-700 text-xs px-2 py-1 rounded-full mb-2", children: book.genre })), _jsxs("div", { className: "flex items-center justify-between", children: [book.rating && (_jsxs("div", { className: "flex items-center gap-1", children: [_jsx("span", { className: "text-yellow-500", children: "\u2B50" }), _jsxs("span", { className: "text-sm text-stone-600", children: [book.rating.toFixed(1), " ", book.totalRatings && `(${book.totalRatings})`] })] })), book.price && (_jsxs("span", { className: "font-semibold text-blue-600", children: [book.price, " K\u010D"] }))] })] })] }, book.id))) }), booksResponse.totalPages > 1 && (_jsxs("div", { className: "text-center text-stone-600 mt-8", children: ["Strana ", booksResponse.page, " z ", booksResponse.totalPages] }))] })) : (_jsxs("div", { className: "text-center py-12", children: [_jsx("div", { className: "text-stone-600 mb-4", children: "\u017D\u00E1dn\u00E9 knihy nenalezeny" }), hasActiveFilters && (_jsx("button", { onClick: onClearFilters, className: "text-blue-600 hover:text-blue-700 transition-colors", children: "Zobrazit v\u0161echny knihy" }))] }))] }));
}
