import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { BookOpen, User, Heart, LogOut, ShoppingCart, Settings } from 'lucide-react';
import { useAuth } from '../hooks/useAuth';
import { useCart } from '../context/CartContext';
export default function Navbar() {
    const { isAuthenticated, logout, isAdmin } = useAuth();
    const { cartCount } = useCart();
    return (_jsx("nav", { className: "bg-white shadow-sm border-b border-stone-200 sticky top-0 z-10", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex justify-between h-16", children: [_jsx("div", { className: "flex items-center", children: _jsxs(Link, { to: "/", className: "flex items-center gap-2 text-blue-600 font-bold text-xl tracking-tight", children: [_jsx(BookOpen, { className: "h-6 w-6" }), _jsx("span", { children: "Knihovna" })] }) }), _jsxs("div", { className: "flex items-center gap-6", children: [_jsxs(Link, { to: "/books", className: "text-stone-600 hover:text-blue-600 transition-colors flex items-center gap-1 font-medium", children: [_jsx(BookOpen, { className: "h-5 w-5" }), _jsx("span", { className: "hidden sm:inline", children: "Knihy" })] }), _jsxs(Link, { to: "/cart", className: "relative text-stone-600 hover:text-blue-600 transition-colors flex items-center gap-1", children: [_jsx(ShoppingCart, { className: "h-5 w-5" }), _jsx("span", { className: "hidden sm:inline", children: "Ko\u0161\u00EDk" }), cartCount > 0 && (_jsx("span", { className: "absolute -top-2 -right-2 bg-red-500 text-white text-xs font-bold rounded-full w-5 h-5 flex items-center justify-center", children: cartCount }))] }), isAuthenticated && (_jsxs(_Fragment, { children: [_jsxs(Link, { to: "/favourites", className: "text-stone-600 hover:text-blue-600 transition-colors flex items-center gap-1", children: [_jsx(Heart, { className: "h-5 w-5" }), _jsx("span", { className: "hidden sm:inline", children: "Obl\u00EDben\u00E9" })] }), _jsxs(Link, { to: "/profile", className: "text-stone-600 hover:text-blue-600 transition-colors flex items-center gap-1", children: [_jsx(User, { className: "h-5 w-5" }), _jsx("span", { className: "hidden sm:inline", children: "Profil" })] }), isAdmin && (_jsxs(Link, { to: "/admin", className: "text-amber-600 hover:text-amber-800 transition-colors flex items-center gap-1 font-medium", children: [_jsx(Settings, { className: "h-5 w-5" }), _jsx("span", { className: "hidden sm:inline", children: "Admin" })] })), _jsxs("button", { onClick: logout, className: "text-stone-600 hover:text-red-600 transition-colors flex items-center gap-1", children: [_jsx(LogOut, { className: "h-5 w-5" }), _jsx("span", { className: "hidden sm:inline", children: "Odhl\u00E1sit" })] })] })), !isAuthenticated && (_jsxs(_Fragment, { children: [_jsx(Link, { to: "/login", className: "text-stone-600 hover:text-blue-600 transition-colors font-medium", children: "P\u0159ihl\u00E1\u0161en\u00ED" }), _jsx(Link, { to: "/register", className: "bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-xl font-medium transition-colors", children: "Registrace" })] }))] })] }) }) }));
}
